#!/usr/bin/env bash
# gen-digests.sh — regenerate digests.env and params.yaml from digests.cue.
#
# digests.cue is the source of truth. This produces two committed artifacts so
# the actual values are visible in git and no consumer needs the cue binary:
#
#   digests.env   KEY=sha256:...   (sourced by scripts, envsubst on manifests)
#   params.yaml   Tekton param defaults for the pinned digests
#
# Empty ("") entries in digests.cue are skipped — they are not yet pinned.
# Idempotent: re-running on a clean tree produces no diff.
#
# Pinned tool: cue (see docs/bootstrap-toolchain.md).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/lib/log.sh
source "$ROOT/scripts/lib/log.sh"

need cue
need jq

CUE_PIN="v0.17.1"
have="$(cue version | awk '/^cue version/ {print $3}')"
[ "$have" = "$CUE_PIN" ] || log_kv level=warn msg="cue $have != pinned $CUE_PIN (docs/bootstrap-toolchain.md)"

cd "$ROOT"

json="$(cue export ./digests.cue --out json)"

# digests.env — non-empty entries only, sorted, with a generated-file header.
{
	echo "# GENERATED by scripts/gen-digests.sh from digests.cue — do not edit."
	echo "$json" | jq -r '
		[
			(.images | to_entries | map({key: (.key | ascii_upcase), value})[]),
			({key: "FRONTEND_REPO",        value: .frontend.repo}),
			({key: "FRONTEND_FIXTURE_SHA", value: .frontend.fixtureSha})
		]
		| map(select(.value != "" and .value != null))
		| sort_by(.key)
		| .[]
		| "\(.key)=\(.value)"
	'
} > digests.env

# params.yaml — Tekton param objects for the non-empty entries.
{
	echo "# GENERATED by scripts/gen-digests.sh from digests.cue — do not edit."
	echo "# Merge these into Task/Pipeline spec.params[].default as digests get pinned."
	echo "params:"
	non_empty="$(echo "$json" | jq -r '[.images | to_entries[] | select(.value != "")] | length')"
	if [ "$non_empty" -eq 0 ]; then
		echo "  [] # none pinned yet"
	else
		echo "$json" | jq -r '
			.images
			| to_entries
			| map(select(.value != ""))
			| sort_by(.key)
			| .[]
			| "  - name: \(.key)-digest\n    type: string\n    default: \"\(.value)\""
		'
	fi
} > params.yaml

log_kv step=gen-digests wrote="digests.env params.yaml" pinned="$(echo "$json" | jq -r '[.images | to_entries[] | select(.value != "")] | length')"
