// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// No standalone defaults: `image` is required and every instance supplies it.
// All other fields default inside templates/config.cue.
values: {}
