#!/usr/bin/env bats
# Tests for scripts/gen-digests.sh and the digests.cue schema.

setup() {
	ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
	cd "$ROOT"
}

@test "digests.cue passes cue vet" {
	run cue vet ./digests.cue
	[ "$status" -eq 0 ]
}

@test "gen-digests.sh is idempotent (no diff on a clean tree)" {
	run scripts/gen-digests.sh
	[ "$status" -eq 0 ]
	run git diff --exit-code -- digests.env params.yaml
	[ "$status" -eq 0 ]
}

@test "generated files carry the do-not-edit header" {
	grep -q "GENERATED by scripts/gen-digests.sh" digests.env
	grep -q "GENERATED by scripts/gen-digests.sh" params.yaml
}

@test "the #Digest constraint rejects a malformed digest" {
	# Constraint copied verbatim from digests.cue — keep in sync.
	run bash -c 'printf "x: =~\"^sha256:[0-9a-f]{64}\$\" & \"sha256:not-hex\"\n" | cue vet -'
	[ "$status" -ne 0 ]
}

@test "the #Digest constraint accepts a well-formed digest" {
	sha="sha256:$(printf '%064d' 0)"
	run bash -c "printf 'x: =~\"^sha256:[0-9a-f]{64}\$\" & \"$sha\"\n' | cue vet -"
	[ "$status" -eq 0 ]
}

@test "digests.cue's #Digest pattern matches this test's copy" {
	grep -qF '=~"^sha256:[0-9a-f]{64}$"' digests.cue
}
